env: ENV_PROD
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
chain:
  chain_id: 421614
  chain_name: "opBNB"
  rpc_url: "https://sepolia-rollup.arbitrum.io/rpc"
  start_block: 0
  offset_block: 3600 # opBNB block time: 1 sec. An offset of 3600 starts fetching blocks from 1 hours ago.
contract:
  addr: "0x773cF326c07b63EdEE1AF7a7d3D4075b1F7f8861"
  tee_addr : "0x7f57004E08ef1702b2b88b87ae01a561ae10F10e"
  topic1: "0x89a3b784b99180438f3b2027aa89e97c3c3ed66e8dc78a555d7013b39caf1a89"
  topic2: "0xb607741c8d9a954d2d7d43f623a61c82253e314e1dc04571dda1881c468e688d"
settings_contract:
  addr: "0x1321641F35F29b140113C59112Fc50364BAcE3f1"
wallet:
  mode: 0
  private_key: ""
  keystore_path: ""
  keystore_password: ""
  reward_claimer_addr: ""
  commission_rate: 0
signature:
  domain_name: "ProtocolService"
  domain_version: "1.0.0"
  expired_time: 3600
gasless_service:
  url: "http://localhost:8080"
